### ISSUE TITLE
other和other2的js和css能不能也打包到相应的文件夹？

### ISSUE THREAD

**Issue by Peter-Success** [flytam/webpack4-multpage-learn#2]

**Comment by flytam** [comment]
@Peter-Success 已经支持了。修改了下。主要修改如下
![image](https://user-images.githubusercontent.com/20512530/45090376-c4f23b80-b141-11e8-98b3-05af85bd4a1d.png)
![image](https://user-images.githubusercontent.com/20512530/45090403-d2a7c100-b141-11e8-9989-716feca920b1.png)
